packages:
  - playground

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver

shellEmulator: true

catalog:
  '@antfu/eslint-config': ^7.6.1
  '@nuxt/devtools': ^3.2.2
  '@nuxt/eslint-config': ^1.15.2
  '@nuxt/kit': ^4.3.1
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/schema': ^4.3.1
  '@nuxt/test-utils': ^4.0.0
  '@types/node': ^24.10.15
  changelogen: ^0.6.2
  eslint: ^10.0.2
  nuxt: ^4.3.1
  typescript: ^5.9.3
  vitest: ^4.0.18
  vue-tsc: ^3.2.5

trustPolicy: no-downgrade
