packages:
  - playground

catalog:
  '@antfu/eslint-config': ^7.7.0
  '@nuxt/devtools': ^3.2.3
  '@nuxt/eslint-config': ^1.15.2
  '@nuxt/kit': ^4.3.1
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/schema': ^4.3.1
  '@nuxt/test-utils': ^4.0.0
  '@types/node': ^24.12.0
  bumpp: ^10.1.0
  defu: ^6.1.4
  changelogen: ^0.6.2
  eslint: ^10.0.3
  nuxt: ^4.3.1
  typescript: ^5.9.3
  unleash-client: ^6.10.1
  vitest: ^4.0.18
  vue-tsc: ^3.2.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver

overrides:
  chokidar: ^5.0.0
  semver: ^7.7.4

shellEmulator: true

trustPolicy: no-downgrade
