export default defineAppConfig({
  seo: {
    titleTemplate: '%s - nuxt-unleash',
    title: 'nuxt-unleash',
    description: 'Edge-first Unleash feature flags for Nuxt',
  },
  header: {
    title: 'nuxt-unleash',
  },
  socials: {
    github: 'https://github.com/adamkasper/nuxt-unleash',
  },
  github: {
    url: 'https://github.com/adamkasper/nuxt-unleash',
    branch: 'main',
    rootDir: 'docs',
  },
  toc: {
    title: 'On this page',
  },
  ui: {
    colors: {
      primary: 'emerald',
      neutral: 'slate',
    },
    icons: {
      arrowDown: 'ph:arrow-down-duotone',
      arrowLeft: 'ph:arrow-left-duotone',
      arrowRight: 'ph:arrow-right-duotone',
      arrowUp: 'ph:arrow-up-duotone',
      caution: 'ph:warning-circle-duotone',
      check: 'ph:check-duotone',
      chevronDoubleLeft: 'ph:caret-double-left-duotone',
      chevronDoubleRight: 'ph:caret-double-right-duotone',
      chevronDown: 'ph:caret-down-duotone',
      chevronLeft: 'ph:caret-left-duotone',
      chevronRight: 'ph:caret-right-duotone',
      chevronUp: 'ph:caret-up-duotone',
      close: 'ph:x-duotone',
      copy: 'ph:copy-duotone',
      copyCheck: 'ph:check-duotone',
      dark: 'ph:moon-duotone',
      drag: 'ph:dots-six-vertical-duotone',
      ellipsis: 'ph:dots-three-duotone',
      error: 'ph:x-circle-duotone',
      external: 'ph:arrow-up-right-duotone',
      eye: 'ph:eye-duotone',
      eyeOff: 'ph:eye-slash-duotone',
      file: 'ph:file-duotone',
      folder: 'ph:folder-duotone',
      folderOpen: 'ph:folder-open-duotone',
      hash: 'ph:hash-duotone',
      info: 'ph:info-duotone',
      light: 'ph:sun-duotone',
      loading: 'ph:circle-notch-duotone',
      menu: 'ph:list-duotone',
      minus: 'ph:minus-duotone',
      panelClose: 'ph:sidebar-simple-duotone',
      panelOpen: 'ph:sidebar-simple-duotone',
      plus: 'ph:plus-duotone',
      reload: 'ph:arrow-counter-clockwise-duotone',
      search: 'ph:magnifying-glass-duotone',
      stop: 'ph:stop-duotone',
      success: 'ph:check-circle-duotone',
      system: 'ph:desktop-duotone',
      tip: 'ph:lightbulb-duotone',
      upload: 'ph:upload-simple-duotone',
      warning: 'ph:warning-duotone',
    },
  },
})
